#ifndef CONFIG_H
#define CONFIG_H


#define WIFI_SSID       "TEMPLATE_WIFI_SSID"
#define WIFI_PASSWORD   "TEMPLATE_WIFI_PASSWORD"


#define BACKEND_HOST    "TEMPLATE_BACKEND_HOST"
#define BACKEND_PORT    TEMPLATE_BACKEND_PORT
#define BACKEND_PATH    "/api/cameras/register"


#define CAMERA_BEARER_TOKEN "TEMPLATE_CAMERA_BEARER_TOKEN"


#define CAMERA_ID       "TEMPLATE_CAMERA_ID"


#define STREAM_PORT     81
#define CONTROL_PORT    80

#endif

